server:
    port: 8888

spring:
  application:
    name: zuul

zuul:
    routes:
        forms:
            path: /mongo/**
            serviceId: http://localhost:8080/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


