server:
    port: 8888

spring:
  application:
    name: zuul

zuul:
    routes:
        forms:
            path: /forms/**
            serviceId: mongo-api
        sidecar:
            path: /api/**
            serviceId: sidecar


eureka:
 client:
  registryFetchIntervalSeconds: 30
  serviceUrl:
   defaultZone: ${EUREKA_SERV:http://dmytriigrishin.me:8090/eureka/}

