server:
    port: 8888

spring:
  application:
    name: zuul

zuul:
    routes:
        forms:
            path: /mongo/**
            serviceId: mongo-api
        cassandra:
            path: /cassandra/**
            url: http://localhost:8542/cassandra
        neo4j:
            path: /neo4j/**
            url: http://localhost:8542/neo4j
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

eureka:
 client:
  registryFetchIntervalSeconds: 30
  serviceUrl:
   defaultZone: ${EUREKA_SERV:http://dmytriigrishin.me:8090/eureka/}

