sidecar:
  #set port of ur app here
  port: 2000
  health-uri: http://localhost:${sidecar.port}/health.json

spring:
  application:
    name: sidecar

eureka:
 client:
  registryFetchIntervalSeconds: 30
  serviceUrl:
   defaultZone: ${EUREKA_SERV:http://138.68.140.160:8090/eureka/}