sidecar:
  #set port of ur app here
  port: 9000
  health-uri: http://localhost:${sidecar.port}/health

spring:
  application:
    name: sidecar

eureka:
 client:
  registryFetchIntervalSeconds: 30
  serviceUrl:
   defaultZone: ${EUREKA_SERV:http://dmytriigrishin.me:8090/eureka/}